### ISSUE TITLE
Grab segments from the original video and concatenate them to create an overview video file.

### ISSUE THREAD

**Issue by InB4DevOps** [BassThatHertz/video-quality-metrics#13]
Hey, 
I read the comment linked below on reddit and it inspired me to make just that:

- take the first (or even two or more) second(s) of every minute of a movie and encode it @ CRF 0 preset ultrafast x264 (which is lossless)
(I chose to encode at CRF 0 because copying via `-ss <timestamp> -i <file> -t <length>` often creates distorted video)
- concatenate those files to a new "overview" video file
- use that as input for VQM

This should give a much better understanding of the overall quality in a movie than just using consecutive seconds.
Is this something you'd like in VQM?

https://www.reddit.com/r/ffmpeg/comments/hu4xkf/a_small_amount_of_data_related_to_encoding_time/fyldikw?utm_source=share&utm_medium=web2x&context=3

**Comment by CrypticSignal** [comment]
> This should give a much better understanding of the overall quality in a movie than just using consecutive seconds.
Is this something you'd like in VQM?

Well, it obviously wouldn't be "better" than using the whole video, but I do see how what you proposed can be useful as it will result in quicker calculation of the quality metrics, since a 1-hour video will be turned into a 60 seconds long video, while still being a decent representation of the original video since a second of every minute in the video is kept.

How much experience do you have with FFmpeg, by the way? Do you know how to grab a second from each minute and combine them to make a new video? I've never done this before, and I'm happy for you to go ahead with this as I see how this feature can be useful, especially for movies where transcoding the whole movie can take quite a while.

**Comment by InB4DevOps** [comment]
Of course it wouldn't be better than the whole movie but it will be better than just having a clip of 10 consecutive seconds.
I have a rough implementation already that just needs a final touch.  
Expect a pull request later today :)

**Comment by CrypticSignal** [comment]
> It will be better than just having a clip of 10 consecutive seconds.

Agreed.
> I have a rough implementation already that just needs a final touch.
> Expect a pull request later today :)

You could make it configurable, e.g. the user can specify the amount of seconds that are captured every minute. For example, 5 seconds every minute instead of 1 second every minute. And/or giving the user the option to specify the time-interval for the segments (e.g. every 30 seconds instead of every minute). But it's not important to add this configurability now, this can be added later.

**Comment by InB4DevOps** [comment]
> You could make it configurable, e.g. the user can specify the amount of seconds that are captured every minute.

Will do.

> And/or giving the user the option to specify the time-interval for the segments (e.g. every 30 seconds instead of every minute).

Will look into that later

How would you call this mode? And do you see this as an individual mode? Oder an optional pre-step? Or even a script on its own?

**Comment by InB4DevOps** [comment]
btw: the current cut mode has the problem, that it can just take `<number of seconds>` from the beginning. How about we replace the cut mode with the "new configurable cut mode"? :) 
This however would not be a real cut mode but a CRF0-reencode mode. This might make the "Size compared to original" column pretty useless because CRF0 ultrafast encodes tend to have a very high bitrate that has nothing to do with the original any more . Problem is that ffmpeg can not cut with I-frames and that leads to distorted cuts. 

This reddit thread pretty much sums up the issue:
https://www.reddit.com/r/ffmpeg/comments/jk6mly/sometimes_distorted_video_begginning_when_using/

**Comment by CrypticSignal** [comment]
We could have a default time interval of 0 which means that by default the whole video is transcoded. If the user wants to use this new feature, they can specify the argument `--interval 60` if they want 1 second to captured every minute, `--interval 30` if they want 1 second to be captured every 30 seconds, etc.

`parser.add_argument('-i', '--interval', type=int, choices=range(0, 60), default=0, help='blah blah.')`

You will probably have to change the value from an integer to a string (using `str(value)`) when passing the value to FFmpeg.
>btw: the current cut mode has the problem, that it can just take <number of seconds> from the beginning. How about we replace the cut mode with the "new configurable cut mode"? :)
This however would not be a real cut mode but a CRF0-reencode mode. This might make the "Size compared to original" column pretty useless because CRF0 ultrafast encodes tend to have a very high bitrate that has nothing to do with the original any more .

Hmm, I guess the "Size compared to original" column isn't that important, because there's still the "Size" column which allows you to compare the size of the transcodes. I wouldn't mind that column being removed and changing the `-t` mode to instead allow the user to specify a start and end time. And then cut the video using CRF 0. The only issue is that this would result in a large file on the user's computer, but we can make the program delete this video just above the `print(f'All done! Check out the ({filename}) folder.')`

**Comment by InB4DevOps** [comment]
> but we can make the program delete this video just above the print(f'All done! Check out the ({filename}) folder.')

I made sure that the clips are deleted, the overview video might be interesting for some so I kept it.

**Comment by CrypticSignal** [comment]
Commit https://github.com/BassThatHertz/video-quality-metrics/commit/89565f4436f66b3f03b9d2eb3740a2471d923e31 has added this feature to Video Quality Metrics. Credit goes to @InB4DevOps.
