### ISSUE TITLE
Small performance increase? 

### ISSUE THREAD

**Issue by MillingtonAllen** [BassThatHertz/video-quality-metrics#30]
Possibly a dumb idea / a lot of work for a little benefit:

Consider calculating VMAF in a separate thread queue and start the next encode while VMAF is being calculated.

I own an AMD Ryzen 3600.  A lot of my encodes only use ~90% of the processor.  Threads bounce around quite a bit though.  I'll often run two CPU video encodes to bring total CPU usage closer to 95%.  My friend says that his i7 9700 also hovers around 80-90%, depending on the encode.  

I suspect that calculating VMAF simultaneous to encoding, you'd get 5% on x265 (and possibly a good bit more on x264) performance improvement after all is said and done.  If a person has an overclocked machine, they'll see more of a benefit (assuming their overclock is stable) than someone running stock.  Modern processors will potentially boost a bit higher in clock if underutilized, but I suspect filling the pipeline / higher utilization will be more performant than the boost clock.

Conjecture:  Intel supposedly has a better pipeline than AMD, so I expect the performance uplift to be more on AMD machines.  I'm also not sure how (locked / stock) Intel CPU will respond as they typically lower base clocks and power limits, particularly when using AVX.

I think I'm more curious about the potential for additional performance than the performance improvement merits XD x265 scales pretty well up to 32 cores / 64 threads, so it's not like there's a ton of people with hardware that is significantly under-utilized by the current implementation.  VMAF seems to be better fill the pipeline (even when running alone), so it's mostly optimizing whatever x264 / x265 can't efficiently use.  

As for implementation, plot generation would probably also move to the VMAF thread due to timing.  I think setting VMAF as lower priority than x265 would eek out best results as VMAF is used to fill the "gap" of whatever x264/ x265 can't fill.  If equal priority, VMAF would finish sooner than long encodes, leaving a the remainder of the encode time under-utilized.  On shorter encodes, it doesn't matter if VMAF lags and is all calculated at the end as it's a more core-efficient workload.

**Comment by InB4DevOps** [comment]
While putting the VMAF analysis into a thread would be fairly easy I wouldn't know where to put the progress of that thread when there is an encode running cuncurrently. Since we're still only a console application (imo) we can not easily show progress of multiple threads in the console output. 
I could be wrong though as I have never done something like that before.

Behind the scenes I am still working on a major change to VQM: soon(tm) we'll have a GUI and then it'd be much easier to show progress of threads..

NOTE: soon is a "Duke Nukem Forever / Cyberpunk 2077" - soon :)

**Comment by MillingtonAllen** [comment]
In windows, I've mostly seen batch files that run and the open additional cmd windows, but that seems to be more when creating a new process rather than threads.

My next guess was pipes and another thread for managing printing, but I'm more familiar with C than python.  From google, people are suggesting pipes, a shared queue, or different print method called curses.

**Comment by InB4DevOps** [comment]
I'll be on holiday the next 3 weeks so I'll have a lot more time for side projects and then I'll have a look at this. Can't promise anything right now but I'll dive into it :)

**Comment by MillingtonAllen** [comment]
The change to multithreading might also help if you guys are interested in AV1 support down the road.  AV1 only uses around 25% to 30% of my CPU, and is as slow, if not slower, than x265.  The ability to spool up a few simultaneous encode threads would save a lot of time.  That being said, AV1 support in FFMPEG is still experimental.  I'm getting some segfaults near the end of some AV1 encodes with the libaom-av1 library, though I need to try with a newer daily build.

**Comment by CrypticSignal** [comment]
Something that I found out today is that, libvmaf v2.0.0 only uses 1 thread by default. See [this issue](https://github.com/Netflix/vmaf/issues/770). I can add an option to allow the user to specify the amount of threads to be used. 

> I suspect that calculating VMAF simultaneous to encoding, you'd get 5% on x265 (and possibly a good bit more on x264) performance improvement after all is said and done. 

Right now, the program works, for example, as follows:
Transcode with CRF x1, calculate the VMAF of achieved with CRF x1. Trancode with CRF x2, calculate the VMAF achieved with x2...

If I understand correctly, you are proposing the following method:
Transcode with CRF x1, transcode with CRF x2 (while this transcode is happening, calculate the VMAF achieved with CRF x1 (which is where the simultaneous aspect comes into play), and so on.

Python's multiprocessing module would be needed for this, because with the threading module, simultaneous CPU-bound tasks are not possible due to the Global Interpreter Lock (GIL). See [this](https://stackoverflow.com/questions/44793371/is-multithreading-in-python-a-myth). I've never used the multiprocessing module before but I can give it a go at some point.

**Comment by MillingtonAllen** [comment]
#
> Something that I found out today is that, libvmaf v2.0.0 only uses 1 thread by default. See [this issue](https://github.com/Netflix/vmaf/issues/770). I can add an option to allow the user to specify the amount of threads to be used.

You can probably detect number of threads available automatically with either the system or the os library.

#
> Right now, the program works, for example, as follows:
> Transcode with CRF x1, calculate the VMAF of achieved with CRF x1. Trancode with CRF x2, calculate the VMAF achieved with x2...
> 
> If I understand correctly, you are proposing the following method:
> Transcode with CRF x1, transcode with CRF x2 (while this transcode is happening, calculate the VMAF achieved with CRF x1 (which is where the simultaneous aspect comes into play), and so on.

That was what I was initially proposing, particularly if you can give cpu priority to the longer video encode over the shorter vmaf calculation.  If vmaf calculation order is maintained, it would be nice if it were possible to append the stats (encode time, min, std_dev, mean) to the table after each vmaf calculation.

Alternatively, having multiple video encodes (two x265 on my 6 core / 12 thread cpu) simultaneously would probably load the CPU more as opposed to the case of one video encode when the vmaf calculation finishes early.  Best case might be having 2 workers, regardless of job type (vmaf, video encode).  At least one of the workers would have preference for vmaf calculations so the graphs are produced in a timely manner.  You'd likely lose the ordering necessary to append to the stats table early, though nothing is lost compared to current implementation of VQM.

The multiple encode / multiple worker method would be better overall, particularly for scaling with high core counts or less efficient encoders. If you think there's a chance of AV1 support in the future, the multiple worker model is the way to go so you don't have to restructure the program's threading again later.

I'm not trying to push AV1.  When encoding at reasonable setting of CPU 5 (before AV1 exponentially increases encode time), I found AV1 to be a lot blurrier than x265 slower for the same bitrate.  I'm sticking with x265 slower for the foreseeable future.

#
> 
> Python's multiprocessing module would be needed for this, because with the threading module, simultaneous CPU-bound tasks are not possible due to the Global Interpreter Lock (GIL). See [this](https://stackoverflow.com/questions/44793371/is-multithreading-in-python-a-myth). I've never used the multiprocessing module before but I can give it a go at some point.

Interesting.  I had tried to use python's subprocess feature to run av1 in a loop, but the AV1 was only using one thread that way.  I wasn't sure if it was detecting the number of threads available wrong or if it was a python thing.  Decided to open a bunch of terminals and manually copy / paste as it was faster for a one-time test.

**Comment by CrypticSignal** [comment]
@MillingtonAllen @InB4DevOps 
Just thought I'd let you guys know that I have added the ability to set the number of threads to use when computing VMAF (with the `--threads` argument) in commit dbc7edf. By default, it will set the number of threads to what Python's `os.cpu_count()` method returns (on my laptop, which has a dual-core Intel i7-3667U with hyperthreading, it returns 4).

I have also added the option of using the AV1 encoder in commit 994bc7b.

**Comment by MillingtonAllen** [comment]
Awesome on the VMAF and AV1

For my multi-process idea, I just realized a huge oversight.  The time calculation will not be accurate if it is based on the system  / wall clock because processing will be split.  Wall / system clock is probably more what's expected as opposed to CPU time (unaffected by multi-process).

Looking into it more, other AV1 test encoders split the video into chunks and render the chunks separately and merge them back together at the end.  This was the thread that I had found:
https://www.reddit.com/r/AV1/comments/ioy32u/av1_beginners_guide/

So far, I've only tested aom AV1 library through ffmpeg.

**Comment by CrypticSignal** [comment]
I currently have little interest in adding multiprocessing to this program. I would like to note that since this issue was opened, VMAF calculation was sped up as libvmaf's `n_threads` option is no longer kept at the default value of 1 but rather set to the number of threads that the user's CPU has. Also:

- On my computer, CPU usage is at 100% during the transcoding and VMAF calculation stages, and therefore I don't think there will be much performance improvement (if any) with multiprocessing.

- Completion time can be reduced with VQM's Overview Mode and/or by skipping frames with the `--subsample` argument.

With that being said, as this is an open-source program, anyone is free fork this repository and implement multiprocessing themselves. To anyone who decides to do this - if you achieve noticeable improvements in completion time, submit a PR.
