### ISSUE TITLE
Error initializing complex filters.

### ISSUE THREAD

**Issue by QuintinShaw** [BassThatHertz/video-quality-metrics#42]
In commit 6c1f273bb248e882bfd631b288691b59fd43b1cc and earlier versions can be used normally.

All versions run after this commit will prompt the following message:

```
python3 main.py -ntm -ovp 00037.m2ts -tvp 00037-65.mkv
--------------------------------------------------------------------------------
Video Quality Metrics
GitHub.com/CrypticSignal/video-quality-metrics
--------------------------------------------------------------------------------
Here's some information about the original video:
Filename: 00037.m2ts
Bitrate: 15.19 Mbps
Framerate: 24000/1001 (23.976023976023978) FPS
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Calculating the VMAF...
[Parsed_libvmaf_2 @ 0x110608cb0] Option 'model' not found                       
[AVFilterGraph @ 0x110608130] Error initializing filter 'libvmaf' with args 'model=path=vmaf_models/vmaf_v0.6.1.json:log_fmt=json:log_path=\[VQM\] 00037-65.mkv/Metrics of each frame.json:n_subsample=1:n_threads=8:feature='
Error initializing complex filters.
Option not found
  0%|                                             | 0/2891 [00:00<?, ? frames/s]
Done!
Traceback (most recent call last):
  File "/Users/x/Movies/video-quality-metrics-master/main.py", line 325, in <module>
    get_metrics_save_table(
  File "/Users/x/Movies/video-quality-metrics-master/metrics.py", line 23, in get_metrics_save_table
    with open(json_file_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '[VQM] 00037-65.mkv/Metrics of each frame.json'
```

**Comment by CrypticSignal** [comment]
Seems to be a simple case of you using an older version of libvmaf which doesn't support the new options format, e.g. `model=path=` instead of the older `model_path=`. 

You can download a newer build of FFmpeg - https://github.com/CrypticSignal/video-quality-metrics#requirements

If downloading a newer build of FFmpeg is not ideal, perhaps due to using a custom build of FFmpeg with encoders/filters not in pre-built binaries, you can edit your local version of VQM to use the old options syntax, simple replace the contents of libvmaf.py with [this](https://raw.githubusercontent.com/CrypticSignal/video-quality-metrics/6c1f273bb248e882bfd631b288691b59fd43b1cc/libvmaf.py).

Whatever you decide to do, please confirm whether the issue has been solved.

I'm considering changing VQM to use the old options syntax, this way it will work with older and the current version libvmaf, however with the current version of libvmaf, you get messages such as the following in the terminal:

`[libvmaf @ 0x7fed95c08e80] The "model_path" option is deprecated: use model='path=...'.`

This is why the change was made in the first place, to tidy up the terminal output.

**Comment by CrypticSignal** [comment]
Seems to be a simple case of you using an older version of libvmaf which doesn't support the new options format, e.g. `model=path=` instead of the older `model_path=`. 

You can download a newer build of FFmpeg - https://github.com/CrypticSignal/video-quality-metrics#requirements

If downloading a newer build of FFmpeg is not ideal, perhaps due to using a custom build of FFmpeg with encoders/filters not in pre-built binaries, you can edit your local version of VQM to use the old options syntax. Simply replace the contents of libvmaf.py with [this](https://raw.githubusercontent.com/CrypticSignal/video-quality-metrics/6c1f273bb248e882bfd631b288691b59fd43b1cc/libvmaf.py).

Whatever you decide to do, please confirm whether the issue has been solved.

I'm considering changing VQM to use the old options syntax, this way it will work with older and the current version of libvmaf, however with the current version of libvmaf, you get messages such as the following in the terminal:

`[libvmaf @ 0x7fed95c08e80] The "model_path" option is deprecated: use model='path=...'.`

This is why the change was made in the first place, to tidy up the terminal output.

**Comment by QuintinShaw** [comment]
The FFmpeg on my mac is already the latest version:
`brew install ffmpeg
Warning: ffmpeg 5.0 is already installed and up-to-date.`
It is not working, just like above message.

When I tried to checkout libvmaf.py to 6c1f273bb248e882bfd631b288691b59fd43b1cc, and as you said it works now.

**Comment by CrypticSignal** [comment]
The error you got tells me that an older version of libvmaf is being used. Maybe you have two builds of FFmpeg installed. Anyway, this is not an issue with VQM, rather it is due to an older version of libvmaf being used, so I'll close this issue. I might revert to using the old options syntax to prevent this error for those who have an older version of libvmaf.

**Comment by mcclumpherty** [comment]
Looking at the relevant ffmpeg [commit](https://github.com/FFmpeg/FFmpeg/commit/3d29724c008d8f27fecf85757152789b074e8ef9) it would appear that if you want to use the v2 libvmaf, you need to be on at least v5.1 of ffmpeg for this to work properly.

![image](https://user-images.githubusercontent.com/744017/188980789-89087631-0098-4143-ac4e-e9b9e1dd008b.png)
