### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'transcoded_video_path'

### ISSUE THREAD

**Issue by gedimiz** [BassThatHertz/video-quality-metrics#44]
After trying to run command:
`python main.py -ntm -iv w_original.MP4 -tv w_placebo.mp4 -ssim -psnr`

Get this error:
`Traceback (most recent call last):
  File "/home/vm/video-quality-metrics/main.py", line 300, in <module>
    output_folder = f"[VQM] {Path(args.transcoded_video_path).name}"
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'transcoded_video_path'. Did you mean: 'transcoded_video'?`

**Comment by faresbouzayen** [comment]
Hey there! It seems that the error is due to the transcoded_video_path attribute not being defined in the argument parser. From your command, it looks like you might have intended to use -tv for the transcoded video file.

Could you check if the argument parser in main.py defines transcoded_video_path or if it should be transcoded_video instead? You might want to replace args.transcoded_video_path with args.transcoded_video in line 300.

**Comment by gedimiz** [comment]
Well, I took this command from very first example here and then did not change anything in main.py, so it's as well default. Basically tried to run mint command wirh mint installation, but with error. :-)
I am no coder unfortunately, it took me a while to get it "running" up to this point, but I am not sure how definition should look like in main.py.
I see only args.transcoded_video_path  and not args.transcoded_video in main.py

**Comment by CrypticSignal** [comment]
@gedimiz [Fixed ](https://github.com/CrypticSignal/video-quality-metrics/commit/da17fdf8c7e5cb4a91c8ab788fb6e7f512ca5ac5) 🙂

If you pull the latest code and run `python main.py -ntm -iv w_original.MP4 -tv w_placebo.mp4 -ssim -psnr` it should work. Let me know if you run into any other issues or if you have any questions.
